baseURL = "https://megascrapper.github.io/pawsey-poster-site/"
languageCode = 'en-au'
title = "Anomaly Detection for Privacy Preserving Time Series Building IoT Data"
theme = ["paige", "hugo-cite"]


[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"

    [[menu.main]]
    identifier = "poster-references"
    name = "Poster References"
    url = "/poster-references"

    [[menu.main]]
    identifier = "plots"
    name = "Plots"
    url = "/plots"


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true
        [markup.goldmark.highlight]
        noclasses = false


[params]
    [params.paige]
        hide_credit_link = true
